[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "distrosa"
authors = [
  {name="Ahmed Attia", email="attia@mcs.anl.gov"},
  {name="Pi-Yueh Chuang", email="pchuang@anl.gov"},
]
description = "Distributional space-parameter sensitivity analysis"
readme = {file="README.md", content-type ="text/markdown"}
license = {text="NONE"}
keywords = ["probability", "sensitivity analysis",]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: Other/Proprietary License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dynamic = ["version",]
requires-python = ">=3.12"
dependencies = ["torch~=2.6", "numpy>=2.1", "psutil>=7.0", "cupy-cuda12x>=13.4"]

[project.urls]
homepage = "https://gitlab.com/ahmedattia/distrosa"

[tool.setuptools.packages]
find = {}

[tool.setuptools_scm]
# leave empty here
